# Generated by Django 4.0.6 on 2022-10-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StdInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=100)),
                ('std_age', models.IntegerField()),
                ('std_city', models.CharField(max_length=100)),
                ('std_contact', models.IntegerField()),
            ],
        ),
    ]
